<!DOCTYPE html>
<html lang="en">

<head>
	<title>impaired-retail</title>

	<meta charset="utf-8" />

	<style type="text/css">
		@page {
			size: A4;
			font-family: EmbArial;
			margin-left: 100px;
			margin-right: 100px;
		}

		body {
			font-family: EmbArial;
		}

		.justify {
			text-align: justify;
		}

		.spaced-text {
			display: block;
			padding-left: 30px;
		}
	 table {
            width: 100%;
            border-collapse: collapse;
        }
     
                
    
        
       .not-bold {
            font-weight: normal;
        }
        
            .italic-note {
            font-size: 11px;
            font-family: EmbArialItalic;
            line-height: 0.5;
            margin-top: 2px;
            margin-bottom: 5px;
        }
        
   
             table {
            width: 100%;
            border-collapse: collapse;
        }
          td {
            padding: 1px;
            vertical-align: top;
        }
                
        
       .not-bold {
            font-weight: normal;
        }
 
        
     .paddingTd {
            padding-left: 10px;
            padding-top: 0;
            padding-bottom: 0;
            }
            
            .paddingVlues {
            padding-left: 5px;
            padding-top: 0;
            padding-bottom: 0;
            }
	</style>
</head>

<body>
	<header style="margin-top: 50px;
      text-align: left;
      margin-bottom: 20px;">
		<div style="display: inline-block">
         	<svg version="1.0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800.000000 185.000000"
				preserveAspectRatio="xMidYMid meet"
				style="vertical-align: middle; margin-left: 5px; width:216px; height:50px;display: inline-block ">

				<g transform="translate(0.000000,185.000000) scale(0.100000,-0.100000)" fill="#5F6062" stroke="none">
					<path fill="#C61846" d="M4713 1829 c-203 -24 -411 -83 -579 -165 -393 -191 -588 -502 -520
			                          -825 54 -252 276 -491 606 -648 586 -280 1403 -245 1883 81 113 77 250 221
			                          291 308 9 19 11 27 4 16 -106 -156 -226 -259 -413 -351 -237 -118 -477 -169
			                          -790 -168 -468 2 -883 146 -1159 404 -247 231 -316 530 -180 789 127 243 430
			                          437 804 516 150 31 336 47 480 41 81 -4 99 -3 60 3 -71 10 -394 10 -487 -1z" />
					<path d="M1105 1408 c-7 -18 -85 -212 -174 -432 -88 -219 -168 -409 -176 -423
			                          -17 -26 -71 -53 -105 -53 -11 0 -20 -4 -20 -9 0 -12 309 -11 316 0 3 5 -10 9
			                          -29 9 -70 0 -71 32 -8 195 l39 100 150 3 149 3 53 -142 c49 -131 52 -143 36
			                          -154 -15 -12 -15 -13 0 -19 25 -10 553 -5 560 5 3 5 -11 9 -30 9 -22 0 -45 9
			                          -62 23 l-27 24 -8 189 c-4 104 -8 244 -8 311 l-1 122 52 -57 c141 -155 635
			                          -642 650 -642 16 0 18 13 19 128 0 70 4 268 7 440 l7 314 24 19 c13 10 36 19
			                          52 19 16 0 29 5 29 10 0 6 -62 10 -165 10 -103 0 -165 -4 -165 -10 0 -5 18
			                          -10 39 -10 23 0 48 -8 62 -19 23 -18 23 -21 32 -331 4 -172 5 -315 2 -318 -3
			                          -4 -10 -1 -14 6 -4 7 -115 122 -247 255 -131 133 -284 288 -338 345 -54 56
			                          -103 102 -107 102 -15 0 -18 -63 -23 -466 -3 -220 -10 -412 -15 -426 -13 -35
			                          -53 -43 -99 -21 -51 25 -77 78 -251 510 -82 204 -154 381 -161 392 -15 30 -29
			                          26 -45 -11z m54 -371 c30 -83 56 -158 59 -164 3 -10 -24 -13 -117 -13 -67 0
			                          -121 3 -121 8 -1 12 115 322 120 322 3 0 29 -69 59 -153z" />
					<path d="M6286 1413 c-7 -16 -84 -203 -170 -417 -86 -213 -166 -406 -177 -428
			                          -13 -26 -32 -44 -54 -54 -46 -19 -69 -18 -61 2 12 32 19 154 9 154 -6 0 -13
			                          -14 -17 -31 -15 -76 -94 -108 -232 -93 -97 10 -110 25 -119 145 -4 52 -5 221
			                          -3 375 3 260 4 284 22 303 13 14 31 21 58 21 21 0 38 5 38 10 0 6 -72 10 -195
			                          10 -123 0 -195 -4 -195 -10 0 -5 13 -10 30 -10 48 0 79 -20 85 -54 4 -17 5
			                          -204 3 -414 l-3 -384 -24 -19 c-13 -10 -36 -19 -53 -19 -16 0 -27 -4 -24 -9 8
			                          -12 916 -13 916 -1 0 6 -9 10 -21 10 -35 0 -59 19 -59 47 0 15 19 77 42 140
			                          l43 113 150 0 150 0 49 -133 c27 -72 51 -138 53 -144 3 -7 -5 -17 -18 -21
			                          l-23 -9 26 -6 c37 -10 508 -6 508 3 0 4 -17 10 -37 14 -58 9 -68 19 -65 69 1
			                          43 60 502 66 522 2 6 27 -42 56 -105 63 -134 237 -479 252 -497 6 -7 14 -10
			                          19 -7 9 5 182 356 264 536 22 48 43 87 46 88 3 0 18 -91 33 -202 15 -112 31
			                          -227 37 -257 13 -77 12 -141 -3 -141 -8 0 -8 -3 -2 -9 14 -15 300 -26 308 -12
			                          5 7 -1 11 -16 11 -51 0 -98 21 -113 50 -14 27 -41 196 -112 687 -29 198 -34
			                          217 -56 193 -8 -8 -85 -163 -172 -345 -86 -181 -163 -341 -170 -355 -12 -24
			                          -21 -10 -159 275 -181 374 -208 427 -223 432 -6 2 -14 -4 -17 -14 -3 -10 -33
			                          -198 -66 -418 -33 -220 -65 -417 -70 -437 -26 -92 -100 -76 -155 32 -13 25
			                          -85 198 -160 385 -160 398 -185 455 -196 455 -5 0 -15 -12 -23 -27z m53 -388
			                          c28 -77 51 -145 51 -152 0 -10 -29 -13 -121 -13 -111 0 -121 1 -114 18 4 9 32
			                          84 63 165 34 92 58 143 63 135 4 -8 30 -76 58 -153z" />
					<path d="M4897 1420 c-229 -58 -266 -295 -74 -464 34 -30 87 -74 117 -98 84
			                          -67 115 -117 115 -186 0 -95 -56 -146 -160 -147 -107 0 -173 56 -190 163 -4
			                          23 -10 42 -14 42 -10 0 -21 -86 -21 -162 0 -54 2 -58 31 -73 40 -21 160 -34
			                          235 -25 162 20 268 145 249 295 -12 100 -58 162 -213 286 -126 101 -152 134
			                          -152 197 0 34 6 49 34 79 31 34 39 37 98 41 47 3 74 0 96 -12 35 -18 82 -75
			                          82 -99 0 -23 11 -47 21 -47 5 0 9 43 9 95 0 94 0 96 -26 105 -38 15 -193 21
			                          -237 10z" />
					<path d="M0 1400 c0 -5 18 -10 39 -10 23 0 48 -8 62 -19 l24 -19 3 -324 c2
			                          -177 -1 -363 -6 -412 -11 -98 -23 -116 -74 -116 -15 0 -28 -4 -28 -9 0 -6 99
			                          -9 238 -8 219 2 241 4 283 23 149 69 210 230 135 358 -30 52 -71 88 -138 122
			                          l-49 25 49 54 c124 136 81 298 -89 334 -64 14 -449 15 -449 1z m416 -71 c80
			                          -73 85 -246 10 -294 -21 -13 -74 -20 -128 -17 l-28 2 0 171 0 171 60 -4 c46
			                          -3 66 -10 86 -29z m4 -384 c134 -69 186 -304 85 -380 -68 -53 -202 -40 -225
			                          20 -12 30 -14 368 -2 379 10 12 109 -2 142 -19z" />
					<path d="M2630 1400 c0 -5 18 -10 40 -10 58 0 80 -26 80 -92 3 -436 -1 -727
			                          -11 -755 -9 -28 -16 -34 -50 -39 -85 -14 -30 -22 146 -22 182 0 243 9 145 22
			                          -37 5 -53 12 -62 29 -14 26 -25 417 -12 417 5 0 15 -9 21 -19 22 -36 269 -315
			                          320 -362 80 -75 101 -82 246 -87 134 -5 162 5 78 27 -94 24 -178 96 -429 370
			                          l-122 133 33 37 c44 48 266 264 297 289 35 27 97 52 131 52 16 0 29 5 29 10 0
			                          6 -58 10 -155 10 -97 0 -155 -4 -155 -10 0 -5 7 -10 15 -10 26 0 16 -43 -21
			                          -90 -35 -45 -283 -300 -292 -300 -7 0 4 344 12 363 5 10 24 20 47 23 88 14 28
			                          24 -146 24 -117 0 -185 -4 -185 -10z" />
					<path d="M4270 1400 c0 -5 13 -10 29 -10 16 0 39 -9 52 -19 l24 -19 0 -399 c0
			                          -305 -3 -403 -13 -420 -8 -15 -26 -25 -52 -29 -87 -14 -31 -22 155 -22 186 -1
			                          263 10 153 20 -92 9 -88 -11 -88 449 0 386 1 400 20 419 11 11 33 20 50 20 17
			                          0 30 5 30 10 0 6 -67 10 -180 10 -113 0 -180 -4 -180 -10z" />
				</g>
			</svg>
            <p style="
            margin-left: 10px;
            font-size: 8px;
            display: inline-block;
            vertical-align: middle;
            line-height: 1;
          ">
				Jika tidak sampai, sila kembalikan kepada:-<br />
				<span style="white-space: nowrap">
					P.O. Box 12176, 50724 Kuala Lumpur, Malaysia
				</span>
			</p>
		</div>
		<div>
			<p class="justify" style="
            font-size: 8px;
            margin-top: 5px;
            margin-left: 5px;
            line-height: 1.2;
          ">
				SULIT &amp; PERSENDIRIAN<br />
				Untuk dibuka oleh Penorima sahaja
			</p>
		</div>
	</header>
	
	<div style="margin-top: 45px; margin-left: 5px;">
	         <p
          class="justify"
          style="
              font-size: 10px;
              font-family: EmbArialBold;
              margin-top: 0;
              margin-bottom: 0;
              max-height: 90px;
              min-height: 90px;
              height: 90px;">
          ${contextVariables.customerNameWithTittle!}
          <br />
          <span>
            <#compress>
              <#if contextVariables.add1?has_content && contextVariables.add1?trim !=''>
                ${contextVariables.add1?html}
                <br />
              </#if>
              <#if contextVariables.add2?has_content && contextVariables.add2?trim !=''>
                ${contextVariables.add2?html}
                <br />
              </#if>
              <#if contextVariables.add3?has_content && contextVariables.add3?trim !=''>
                ${contextVariables.add3?html}
                <br />
              </#if>
              <#if contextVariables.add4?has_content && contextVariables.add4?trim !=''>
                ${contextVariables.add4?html}
                <br />
              </#if>
              <#if contextVariables.add5?has_content && contextVariables.add5?trim !=''>
                ${contextVariables.add5?html}
                <br />
              </#if>
              <#if contextVariables.add6?has_content && contextVariables.add6?trim !=''>
                ${contextVariables.add6?html}
              </#if>
            </#compress>
          </span>
        </p>
	</div>

	<div style="margin-left: 5px; margin-top: 50px;"> 


    <div style="display: inline-block; font-size: 12px; font-family: EmbArial;line-height: 1.2;">
       
<table>
  <tr>
    <th class="not-bold">Tarikh</th>
    <td class="paddingTd">:</td>
    <td class="paddingVlues">${contextVariables.date!}</td>
  </tr>
    <tr>
        <th class="not-bold">No. Akaun</th>
        <td class="paddingTd">:</td>
        <td class="paddingVlues">${contextVariables.accountNo!}</td>
    </tr>
  <tr>
    <td class="not-bold" style="white-space: nowrap; vertical-align: top; padding: 0; line-height:1.2;">Nama / Alamat pelanggan</td>
    <td class="paddingTd">:</td>
    <td style="line-height: 1.2;" class="paddingVlues">
     	<#compress>
     	
     	<#if contextVariables.customerNameWithTittle?has_content && contextVariables.customerNameWithTittle?trim !=''>
                ${contextVariables.customerNameWithTittle?html}
                <br />
              </#if>
     	
              <#if contextVariables.add1?has_content && contextVariables.add1?trim !=''>
                ${contextVariables.add1?html}
                <br />
              </#if>
              <#if contextVariables.add2?has_content && contextVariables.add2?trim !=''>
                ${contextVariables.add2?html}
                <br />
              </#if>
              <#if contextVariables.add3?has_content && contextVariables.add3?trim !=''>
                ${contextVariables.add3?html}
                <br />
              </#if>
              <#if contextVariables.add4?has_content && contextVariables.add4?trim !=''>
                ${contextVariables.add4?html}
                <br />
              </#if>
              <#if contextVariables.add5?has_content && contextVariables.add5?trim !=''>
                ${contextVariables.add5?html}
                <br />
              </#if>
              <#if contextVariables.add6?has_content && contextVariables.add6?trim !=''>
                ${contextVariables.add6?html}
                <br />
              </#if>
            </#compress>
    </td>
  </tr>
  
 
   <tr>
        <th class="not-bold">Jenis Pembiayaan</th>
        <td class="paddingTd">:</td>
        <td class="paddingVlues">${contextVariables.typeOfFinancing!}</td>
    </tr>
         <tr>
        <th class="not-bold" style="padding: 0;">Jumlah Baki</th>
        <td class="paddingTd">:</td>
        <td class="paddingVlues">RM ${contextVariables.balance!} <span style="margin-left:200px;">(Setakat ${contextVariables.asFarAsDate!})</span> </td>
    </tr>
  <tr>
        <td colspan="3" class="not-bold">
            <p class="italic-note" style="margin: 1; font-size: 12px;">(Tidak termasuk kos guaman/ kos-kos lain yang belum dituntut -&#160;sekiranya ada)</p>
        </td>
    </tr>
</table>



    </div>
      
<div style="overflow: hidden;">
    <p style="font-size: 11px; display: inline;">Tuan/Puan,</p>
    <span style="font-size: 12px; font-family: EmbArialBold; float: right;">"TANPA PREJUDIS"</span>
</div>


    <p style="font-size: 12px; font-family: EmbArialBold; line-height: 0.5;margin-top: 20px;">
      <u>PER : NOTIS&#160;PERLANTIKAN&#160;AGENSI&#160;KUTIPAN&#160;HUTANG </u>
    </p>

    <div>
      <p class="justify" style="font-size: 12px; line-height: 1.2;margin-top: -5px;">
        Harap maklum, Bank Islam Malaysia Berhad akan melantik Agensi Kutipan Hutang dibawah untuk membuat kutipan
        tunggakan/baki pembiayaan tuan/ puan, sekiranya tunggakan gagal untuk diselesaikan dalam tempoh Tujuh (7) hari dari
        tarikh surat ini:
      </p>

      <div style="display: inline-block;font-size: 12px; font-family: EmbArial;line-height: 1.2;margin-top: -8px;">
    <table>
  <tr>
    <td style="font-family: EmbArialBold;">Nama Agensi</td>
    <td class="paddingTd">:</td>
    <td class="paddingVlues">${contextVariables.dcaName!}</td>
  </tr>
  <tr>
    <td style="font-family: EmbArialBold;">Alamat</td>
    <td class="paddingTd">:</td>
 <td class="paddingVlues"><span> ${contextVariables.address!}</span></td>

  </tr>
  <tr>
    <td style="font-family: EmbArialBold;">No. Telefon</td>
    <td class="paddingTd">:</td>
    <td class="paddingVlues">${contextVariables.agencyTelNo!}</td>
  </tr>
  <tr>
    <td style="font-family: EmbArialBold;">No. Faks</td>
    <td class="paddingTd">:</td>
    <td class="paddingVlues">${contextVariables.agencyFaxNo!}</td>
  </tr>
</table>

      </div>

      <p class="justify" style="font-size: 12px; line-height: 1.2;margin-top: 10px;">
   Sila pastikan Agensi Kutipan Hutang memperkenalkan diri dan menunjukksn kad wakil kuasa
ketika berurusan atau berjumpa dengan tuan/ puan.
      </p>
      <p class="justify" style="font-size: 12px; line-height: 1.2; ">
    Sila ambil perhatian, sekiranya tuan/puan gagal membayar tunggakan tersebut dalam masa
yang diberikan, tuan/puan adalah bertanggungjawab untuk menanggung kos guamen yang
terlibat di dalam urusan pengendalian akaun yang tertunggak oleh Bank Islam.</p>

      <p  class="justify" style="font-size: 12px; line-height: 1.2;">PERHATIAN, sekiranya bayaran yang dibuat adalah melalui Cek/ Bank Deraf, pembayaran<br/>
     <span> hendaklah dibuat di atas nama Bank Islam Malaysia Berhad.</span> <br/>
      <span> Sila abaikan notis ini jikalau pembayaran telah dilakukan.</span> </p>
      
  
    <p class="justify" style="font-size: 12px;">
				Sebarang pertanyaan, sila hubungi pegawai-pegawai Bank Islam seperti berikut :<br /> 
				1) <span>${contextVariables.nameOfBankOfficerOne!} ( ${contextVariables.telephoneNumberOne!} )</span>&#160;&#160;&#160;&#160;
				2) <span>${contextVariables.nameOfBankOfficerTwo!} ( ${contextVariables.telephoneNumberTwo!} )</span> </p>


 <p class="justify" style="font-size: 11px;margin-top: 10px;line-height: 1.2;"><span>Yang benar,</span><br/>
       <span style="font-size: 11px;font-family: EmbArialBold;">BANK&#160;ISLAM&#160;MALAYSIA&#160;BERHAD &#160;&#160;(98127-X)</span><br/>
       <span>S.K.</span> <span  style="margin-left:60px">(Penjamin - Jika ada)</span>
         </p>


      <p class="justify" style="font-size: 11px;margin-top: 10px;line-height: 1.2;">Agensi Kaunseling dan Pengurusan Kredit telah ditubuhkan oleh Bank Negara Malaysia untuk menyediakan perkhidmatan pengurusan kewangan,
       kaunseling kredit, pendidikan kewangan dan penstrukturan semula pembiayaan secara percuma kepada Individu. Untuk pertanyaan, 
       sila hubungi talian 1-300-88-2575.</p>
       
       <p class="justify" style="font-size: 11px;margin-top: 10px;line-height: 1.2;">SURAT INI ADALAH CETAKAN KOMPUTER. TANDATANGAN BERKUASA TIDAK DIPERLUKAN.</p>
    </div>

  </div>

</body>

</html>