<!DOCTYPE html>
<html lang="en">

<head>
	<title>Dca Notice-Impaired Bic</title>

	<meta charset="utf-8" />

	<style type="text/css">
		@page {
			size: A4;
			font-family: EmbArial;
			
		}

		body {
			font-family: EmbArial;
		}

		.justify {
			text-align: justify;
		}

		.spaced-text {
			display: block;
			padding-left: 30px;
		}
	 table {
            border-collapse: collapse;
        }
     
                
    
        
       .not-bold {
            font-weight: normal;
        }
        
            .italic-note {
            font-size: 11px;
            font-family: EmbArialItalic;
            line-height: 0.5;
            margin-top: 2px;
            margin-bottom: 5px;
        }
        
   
             table {
            width: 100%;
            border-collapse: collapse;
        }
          td {
            padding: 1px;
            vertical-align: top;
        }
                
        
       .not-bold {
            font-weight: normal;
        }

        
     .paddingTd {
            padding-left: 10px;
            padding-top: 0;
            padding-bottom: 0;
            }
                 .paddingValue {
            padding-left: 10px;
            padding-top: 0;
            padding-bottom: 0;
            }
            
            ul {
    list-style-type: none;
    padding: 0;
    margin-left: 10px;
    font-size: 13px;
}

ul li {
    position: relative;
    padding-left: 1.5em;
    margin-bottom: 1em; 
}

ul li::before {
    content: "\25A1"; 
    position: absolute;
    left: 1;
    top: -0.4em; 
    font-size: 1.5em;
    font-weight: bold;
 
    

}
     .table-style {
  border-collapse: collapse;
  margin-top: 20px;
}

.th-style, .td-style {
  border: 1px solid black;
  text-align: center;
  padding: 1px;
}

.th-style {
  background-color: #f2f2f2;
}

.text-right {
  text-align: right;
}

.text-center {
  text-align: center;
}

.caption-style {
  font-weight: bold;
  margin-bottom: 10px;
}

.spaced-paragraph {
  margin: 0 0 10px;
}

td[colspan="4"] {
  text-align: left;
}       



	</style>
</head>

<body style="margin-top: 70px;">	
	<div>
	<div class="justify" style="font-size: 13px; line-height: 1.2;display: inline-block;">
	 <table>
  <tr>
    <td style="font-size: 13px;">Rujukan Kami</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">Column A</td>
  </tr>
    <tr>
    <td style="font-size: 13px;">Tarikh</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">Column B</td>
  </tr>
  </table>
	</div>
 <p style="font-family: EmbArialBold;">SULIT DAN PERSENDIRIAN</p>
 
 <div style="margin-top: 30px;">
	         <p
          class="justify"
          style="
              font-size: 14px;
              font-family: EmbArialBold;
              margin-top: 0;
              margin-bottom: 0;
              max-height: 100px;
              min-height: 100px;
              ">
          ${contextVariables.name}
          <br />
          <span>
        <#compress>
              <#if contextVariables.add1?has_content && contextVariables.add1?trim !=''>
                ${contextVariables.add1?html}
                <br />
              </#if>
              <#if contextVariables.add2?has_content && contextVariables.add2?trim !=''>
                ${contextVariables.add2?html}
                <br />
              </#if>
              <#if contextVariables.add3?has_content && contextVariables.add3?trim !=''>
                ${contextVariables.add3?html}
                <br />
              </#if>
              <#if contextVariables.add4?has_content && contextVariables.add4?trim !=''>
                ${contextVariables.add4?html}
                <br />
              </#if>
              <#if contextVariables.poskod?has_content && contextVariables.poskod?trim !=''>
                ${contextVariables.poskod?html}
                <br />
              </#if>
              <#if contextVariables.city?has_content && contextVariables.city?trim !=''>
                ${contextVariables.city?html}
              </#if>
            </#compress>
          </span>
        </p>
	</div>
	<p class="justify" style="font-size: 12px;font-family: EmbArial">ﻪﺘﺎﻜﺮﺒﻮﷲﺍﺔﻤﺤﺭﻮﻡﻜﻴﻠﻋﻢﻼﺴﻠﺍ /Salam Sejahtera</p>
	<p class="justify" style="font-size: 12px; line-height: 1.2;font-family: EmbArial">Tuan/Puan,</p>
	<p class="justify" style="font-size: 12px; line-height: 1.2;font-family: EmbArialBold">PENSTRUKTURAN SEMULA KEMUDAHAN PEMBIAYAAN PERIBADI</p>
	      <div style="display: inline-block;font-size: 12px; font-family: EmbArial;line-height: 1.2;margin-top: -8px;">
    <table>
  <tr>
    <td style="font-family: EmbArialBold;">PELANGGAN</td>
    <td class="paddingTd">:</td>
    <td>Column C</td>
  </tr>
  <tr>
    <td style="font-family: EmbArialBold;">NO KAD PENGENALAN </td>
    <td class="paddingTd">:</td>
 <td><span>Column D</span></td>

  </tr>
  <tr>
    <td style="font-family: EmbArialBold;">KEMUDAHAN</td>
    <td class="paddingTd">:</td>
    <td>PEMBIAYAAN PERIBADI</td>
  </tr>
  <tr>
    <td style="font-family: EmbArialBold;">NO AKAUN BARU</td>
    <td class="paddingTd">:</td>
    <td>Column E</td>
  </tr>
</table>
      </div>

<hr style="height: 1px; border: none; background-color: #000; width:100%"/>
     <p class="justify" style="font-size: 12px; line-height: 1.2;">Perkara di atas dan surat tawaran daripada Agensi Kaunseling dan Pengurusan Kredit (“AKPK”) kepada Tuan/Puan bertarikh «Date_Lo_AKPK»_Column K adalah dirujuk.</p>
	<p class="justify" style="font-size: 12px; line-height: 1.2;">Sukacita dimaklumkan bahawa Bank Islam Malaysia Berhad (atau“Bank Islam”) di atas budi bicaranya telah bersetuju dengan permohonan Penstrukturan Semula Kemudahan Pembiayaan Tuan/Puan seperti yang telah dibincangkan dan dipersetujui antara pihak Tuan/Puan dan pihak AKPK. </p>
	<p class="justify" style="font-size: 12px; line-height: 1.2;">Berikut adalah perincian maklumat Penstrukturan Semula Kemudahan Pembiayaan Peribadi Tuan/Puan:</p>
	<p  class="justify" style="font-size: 12px; line-height: 1.2; font-family: EmbArialBold;">1. METODOLOGI PENSTRUKTURAN SEMULA</p>
	<p class="justify" style="font-size: 12px; line-height: 1.2;">Penstrukturan semula jumlah prinsipal yang belum dijelaskan bersama dengan caj-caj lain seperti caj guaman dari kemudahan sedia ada kepada kemudahan yang distrukturkan semula dibawah perlaksanaan pembiayaan Tawarruq yang baharu (Kemudahan Penstrukturan Semula) pada Harga Jualan yang dipersetujui yang mana perlu dibayar oleh Tuan/Puan secara terma tertangguh.</p>
	<p class="justify" style="font-size: 12px; line-height: 1.2;">Membawa kehadapan Keuntungan Terakru dan Ta’widh (“Amaun Terakru Yang Belum Dijelaskan”)_Column AL dari kemudahan sedia ada dengan tanpa caj keuntungan tambahan yang dikenakan sebagaimana peraturan yang ditetapkan oleh Majlis Penasihat Shariah, Bank Negara Malaysia (SAC BNM).
Dibawah Metodologi Penstrukturan Semula, Tuan/Puan perlu:</p>
<p class="justify" style="font-size: 12px; line-height: 1.2;">	Membuat bayaran ansuran bagi Kemudahan Penstrukturan Semula dan menyelesaikan Amaun Terakru Yang Belum Dijelaskan seperti yang diperincikan dalam jadual pembayaran di bahagian (4) berdasarkan Bayaran Harga Jualan Bank dibawah.</p>
	
	</div>
	 <table class="table-style">
    <thead>
      <tr>
        <th class="th-style" rowspan="2">Kemudahan Sedia Ada</th>
        <th class="th-style" rowspan="2">No akaun</th>
        <th class="th-style" colspan="5">Harga Jualan Bank Islam yang belum dijelaskan sehingga tarikh </th>
      </tr>
      <tr>
        <th class="th-style">Prinsipal (RM)</th>
        <th class="th-style">Lain-lain caj / Kos pelbagai (RM)</th>
        <th class="th-style">Keuntungan Terakru (RM)</th>
        <th class="th-style">Ta'widh (RM)</th>
        <th class="th-style">jumlah (RM)</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td class="td-style">Pembiayaan Peribadi</td>
        <td class="td-style">XXXXXXXXXXX</td>
        <td class="td-style">278,268.39</td>
        <td class="td-style">0</td>
        <td class="td-style">0</td>
        <td class="td-style">0</td>
        <td class="td-style">278,268.39</td>
      </tr>
    </tbody>
  </table>
<p style="font-size: 12px;font-family: EmbArialBold;">2. KEMUDAHAN PENSTRUKTURAN SEMULA</p>
<p class="justify" style="font-size: 12px;font-family: EmbArialBold;">TUJUAN PEMBIAYAAN</p>
<p class="justify" style="font-size: 12px;font-family: EmbArial;">Amaun Pembiayaan akan digunakan untuk penyelesaian Baki Hutang Akaun Peribadi (Nombor Akaun: «Acc_No_lama»)_Column M berjumlah RM«Prinsipal» setakat «Date_Released_Disbursed».</p>
	
	  <table style="border-collapse: collapse; border: 1px solid black;">
  <tr>
    <td style="border: 1px solid black;">Kemudahan Penstrukturan Semula</td>
    <td style="border: 1px solid black;">(RM)</td>
  </tr>

   <tr>
    <td style="border: 1px solid black;"><div >1) Amaun Prinsipal yang Distrukturkan Semula</div>
    <div style="margin-top:20px;">2) Lain-lain Caj / Kos Pelbagai</div>
     </td>
   
   
   <td style="border: 1px solid black;"><div>«Prinsipal»_Column AA</div>
    <div style="margin-top:20px;" >«Lainlain_caj__Kos_pelbagai_RM»_Column AB</div>
     </td>  </tr>
    <tr>
    <td style="border: 1px solid black; text-align: right;font-family: EmbArialBold;">Jumlah</td>
    <td style="border: 1px solid black;">«Jumlah_RM_Kemudahan_Penstrukturan_Semu»_Column AF</td>
  </tr>
</table>
    
	   <p class="justify" style="font-size: 12px;font-family: EmbArialBold;">HARGA BELIAN BANK</p>
                <p class="justify" style="font-size: 12px;font-family: EmbArial;">RM«Amt_Disbursed»_Column L</p>
        <p class="justify" style="font-size: 12px;font-family: EmbArialBold;"><u>HARGA JUALAN BANK</u></p>

<p style="font-size: 12px;">RM«Selling_Price»_Column N</p>
<p style="font-size: 12px;">Tempoh pembiayaan ialah selama «Tempoh_Fin» bulan_Column O</p>
<p style="font-size: 12px;font-family: EmbArialBold;"><u>3. BAYARAN AMAUN TERAKRU YANG BELUM DIJELASKAN</u></p>
<p style="font-size: 12px;">Amaun Terakru Yang Belum Dijelaskan daripada Kemudahan sedia ada perlu di bayar oleh Tuan/Puan:</p>


<table style="border-collapse: collapse; border: 1px solid black;">
  <tr>
    <td style="border: 1px solid black;background-color: #f2f2f2;">Jumlah Amaun Terakru Yang Belum Dijelaskan (RM)</td>
    <td style="border: 1px solid black;color:red;">«JUMLAH_AMAUN_TERAKRU_YANG_BELUM_DIJELASK»</td>
  </tr>
</table>
 <p class="justify" style="font-size: 12px;">Amaun Terakru Yang Belum Dijelaskan di atas dikira berdasarkan penstrukturan semula Kemudahan sedia ada sehingga «Date_Released_Disbursed»_Column B</p>
<p class="justify" style="font-size: 12px;font-family: EmbArialBold;">3. <u>CARA BAYARAN DAN KADAR KEUNTUNGAN</u></p>
<p class="justify" style="font-size: 12px;">Bank Islam bersetuju untuk melaksanakan jadual pembayaran pada Kadar Keuntungan Efektif «Profit»%_Column P seperti yang diluluskan oleh pihak AKPK.</p>
<p class="justify" style="font-size: 12px;">Jumlah ansuran bulanan dibawah Kemudahan Penstrukturan Semula dan Amaun Terakru Yang Belum Dijelaskan adalah seperti berikut:</p>

<table style="border: 1px solid black; table-layout: fixed; width:">
  <tr>
    <td style="border: 1px solid black;  background-color: #f2f2f2; font-family: EmbArialBold; word-break: break-all;">Dari</td>
    <td style="border: 1px solid black;  background-color: #f2f2f2; font-family: EmbArialBold; word-break: break-all;">Hingga</td>
    <td style="border: 1px solid black;  background-color: #f2f2f2; font-family: EmbArialBold; word-break: break-all;">Tempoh (Bulan)</td>
    <td style="border: 1px solid black;  background-color: #f2f2f2; font-family: EmbArialBold; word-break: break-all;">Ansuran Bulanan (RM)</td>
    <td style="border: 1px solid black;  background-color: #f2f2f2; font-family: EmbArialBold; word-break: break-all;">Jumlah (RM)</td>
  </tr>
  <tr>
    <td style="border: 1px solid black;">Column Q</td>
    <td style="border: 1px solid black; ">Column R</td>
    <td style="border: 1px solid black; ">Column S</td>
    <td style="border: 1px solid black; ">Column T</td>
    <td style="border: 1px solid black; ">Column U</td>
  </tr>
  <tr>
    <td colspan="4" style="border: 1px solid black;">JUMLAH AMAUN TERAKRU YANG BELUM DIJELASKAN</td>
    <td style="border: 1px solid black;">Column AL</td>
  </tr>
</table>

<p class="justify" style="font-size: 12px;">Akaun Tuan/Puan akan diklasifikasikan sebagai penstrukturan semula dibawah Program Pengurusan Kredit, Agensi Kaunseling &amp; Pengurusan Kredit (AKPK) dan di Pusat Sistem Maklumat Rujukan Kredit (CCRIS) Bank Negara Malaysia. Klasifikasi ini boleh memberi implikasi ke atas permohonan kredit Tuan/Puan di masa akan datang.</p>
<p class="justify" style="font-size: 12px;"> Walau bagaimanapun, sekiranya pihak Tuan/Puan tidak lagi dibawah Program Pengurusan Kredit AKPK, Bank Islam berhak pada bila-bila masa dan dari semasa ke semasa dengan notis bertulis mengubah Kadar Keuntungan Efektif kepada kadar yang tidak melebihi Kadar Keuntungan Siling «Ceiling_Rate_System»%_Column W seperti yang termaktub didalam klausa 6(a) Terma-Terma dan Syarat-Syarat Untuk Penstrukturan Semula Kemudahan Di Bawah Agensi Kaunseling dan pengurusan Kredit (“AKPK”). Perubahan terhadap Kadar Keuntungan Efektif akan mengubah jumlah ansuran bulanan Tuan/Puan</p>
<p class="justify" style="font-size: 12px;">Penstrukturan Semula Kemudahan Pembiayaan ini adalah tertakluk kepada Terma-Terma Dan Syarat-syarat Untuk Penstrukturan Semula Kemudahan Di Bawah Agensi Kaunseling Dan Pengurusan Kredit (“AKPK”) yang telah diakui penerimaan dan pengakuan oleh Tuan/Puan pada «Aqad_Date»_Column X.</p>
<p class="justify" style="font-size: 12px;">Adalah dimaklumkan bahawa penstrukturan semula ansuran bulanan akan menyebabkan pengurangan pada kadar yang perlahan ke atas baki amaun pembiayaan dan akan mengakibatkan jumlah kadar keuntungan efektif yang dibayar sepanjang tempoh pembiayaaan akan menjadi lebih tinggi. (akan tetapi jumlah pembayaran tidak akan melebihi daripada harga jualan yang telah dipersetujui)</p>
<p class="justify" style="font-size: 12px;">Adalah dimaklumkan bahawa Perlindungan Takaful Tuan/Puan akan diteruskan sehingga tamat tempoh pembiayaan asal. Walau bagaimanapun Tuan/Puan perlu merujuk kepada Syarikat Takaful sekiranya Tuan/Puan memerlukan lanjutan tempoh perlindungan Takaful sedia ada berikutan lanjutan kepada tempoh pembiayaan di bawah penstrukturan semula.</p>
<p class="justify" style="font-size: 12px;">Sekiranya Tuan/Puan memerlukan sebarang maklumat lanjut, sila hubungi pegawai kami, Mohamad Firdaus Osman di talian 03-2688 2648 atau Mohd Daniel Abdul Samat di talian 03-2782 1391.</p>
<p class="justify" style="font-size: 12px;">Sekian, terima kasih.</p>
<p class="justify" style="font-size: 12px;">Yang Benar,</p>
<p class="justify" style="font-size: 12px;">“AMANAH TERJAMIN.NILAI TERHASIL.”</p>
<p class="justify" style="font-size: 12px; font-family: EmbArialBold;">BANK ISLAM MALAYSIA BERHAD</p>
<p class="justify" style="font-size: 12px;">(Surat ini adalah cetakan berkomputer dan tidak memerlukan tandatangan)</p>
</body>

</html>