<!DOCTYPE html>
<html lang="en">

<head>
	<title>Dca Notice-Impaired Bic</title>

	<meta charset="utf-8" />

	<style type="text/css">
		@page {
			size: A4;
			font-family: EmbArial;
			margin-left: 100px;
			margin-right: 100px;
		}

		body {
			font-family: EmbArial;
		}

		.justify {
			text-align: justify;
		}

		.spaced-text {
			display: block;
			padding-left: 30px;
		}
	 table {
            width: 100%;
            border-collapse: collapse;
        }
     
                
    
        
       .not-bold {
            font-weight: normal;
        }
        
            .italic-note {
            font-size: 11px;
            font-family: EmbArialItalic;
            line-height: 0.5;
            margin-top: 2px;
            margin-bottom: 5px;
        }
        
   
             table {
            width: 100%;
            border-collapse: collapse;
        }
          td {
            padding: 1px;
            vertical-align: top;
        }
                
        
       .not-bold {
            font-weight: normal;
        }

        
     .paddingTd {
            padding-left: 10px;
            padding-top: 0;
            padding-bottom: 0;
            }
                 .paddingValue {
            padding-left: 10px;
            padding-top: 0;
            padding-bottom: 0;
            }
            
            ul {
    list-style-type: none;
    padding: 0;
    margin-left: 10px;
    font-size: 13px;
}

ul li {
    position: relative;
    padding-left: 1.5em;
    margin-bottom: 1em; 
}

ul li::before {
    content: "\25A1"; 
    position: absolute;
    left: 1;
    top: -0.3em; 
    font-size: 1.5em;
    font-weight:480;
 
    

}
            
	</style>
</head>

<body style="margin-top: 70px;">	
	<div>
	<div class="justify" style="font-size: 13px; line-height: 1.2;display: inline-block;">
	 <table>
  <tr>
    <td style="font-size: 13px;">No. Akaun</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column B</td>
  </tr>
    <tr>
    <td style="font-size: 13px;">Tarikh</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column C</td>
  </tr>
  </table>

	</div>
	<div style="margin-top: 30px;">
	         <p
          class="justify"
          style="
              font-size: 13px;
              font-family: EmbArialBold;
              margin-top: 0;
              margin-bottom: 0;
              max-height: 90px;
              min-height: 90px;
              height: 90px;              
              ">
          ${contextVariables.name}<span style="margin-left: 250px;">“TANPA PREJUDIS”</span>
          <br />
          <span>
            <#compress>
              <#if contextVariables.add1?has_content && contextVariables.add1?trim !=''>
                ${contextVariables.add1?html}
                <br />
              </#if>
              <#if contextVariables.add2?has_content && contextVariables.add2?trim !=''>
                ${contextVariables.add2?html}
                <br />
              </#if>
              <#if contextVariables.add3?has_content && contextVariables.add3?trim !=''>
                ${contextVariables.add3?html}
                <br />
              </#if>
              <#if contextVariables.add4?has_content && contextVariables.add4?trim !=''>
                ${contextVariables.add4?html}
                <br />
              </#if>
              <#if contextVariables.add5?has_content && contextVariables.add5?trim !=''>
                ${contextVariables.add5?html}
                <br />
              </#if>
              <#if contextVariables.add6?has_content && contextVariables.add6?trim !=''>
                ${contextVariables.add6?html}
              </#if>
            </#compress>
          </span>
        </p>
	</div>
	<p style="font-size: 13px;">Tuan/Puan,</p>
	
	<div  style="display: inline-block;font-size: 13px; font-family: EmbArial;line-height: 1.2;">
	<table> 
	 <tr>
    <td style="font-family: EmbArialBold;">Perkara</td>
    <td class="paddingTd">:</td>
    <td  style="font-family: EmbArialBold;" class="paddingValue">PERMOHONAN PENJADUALAN &amp; PENSTRUKTURAN SEMULA PEMBIAYAAN
 (Type of financing – column J)</td>
  </tr>
  <tr>
    <td style="font-family: EmbArialBold;">Pelanggan</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column D</td>
  </tr>
    <tr>
    <td style="font-family: EmbArialBold;">No. Akaun</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column B</td>
  </tr>
     <tr>
    <td style="font-family: EmbArialBold;">Kemudahan</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column J</td>
  </tr>
</table>
	</div>
	
	<div
    style="width: 100%; border: none; border-top: 0.5px solid; border-color: black; margin-bottom: 15px; margin-top: 15px;">
</div>

	<p style="font-size: 13px; font-family: EmbArial;">Perkara di atas adalah dirujuk.</p>
	<p style="font-size: 13px; font-family: EmbArial;" class="justify">Adalah &#160;dimaklumkan bahawa permohonan Tuan/Puan untuk mendapat
pengurangan ansuran melalui Penjadualan dan Penstrukturan Semula telah
dibatalkan oleh pihak Bank di atas sebab berikut;</p>
	

<ul>
  <li>
    <p class="justify">Faktor umur Tuan/Puan melebihi had umur yang ditetapkan.</p>
  </li>
  <li>
    <p class="justify">Tuan/Puan gagal menyerahkan dokumen yang diperlukan dalam tempoh 14
hari dari tarikh arahan e-mel yang dikeluarkan oleh pihak Bank.</p>
  </li>
  <li>
    <p class="justify">Tuan/Puan gagal dihubungi selepas 14 hari dari tarikh panggilan pertama
dibuat oleh pihak Bank.</p>
  </li>
  <li>
    <p class="justify">Jumlah perbelanjaan / komitmen kewangan melebihi daripada jumlah
pendapatan.</p>
  </li>
  <li>
    <p class="justify">Jumlah pendapatan melebihi daripada jumlah perbelanjaan / komitmen
kewangan</p>
  </li>
  <li>
    <p class="justify">Pembiayaan Tuan/Puan dibawah Program Penjadualan Semula kurang satu (1) tahun dari tarikh kelulusan Program tersebut atau Program Penyelarasan Tunggakan dan Lanjutan Tempoh Pembiayaan kurang satu (1) tahun dari tarikh notis program tersebut.</p>
  </li>
</ul>
<p style="font-size: 13px; font-family: EmbArial;margin-top:25px;" class="justify">Pihak Bank menyarankan agar Tuan/Puan mendapatkan bantuan penyelesaian
kewangan daripada pihak Agensi Kaunseling Dan Pengurusan Kredit (AKPK) yang
telah ditubuhkan oleh Bank Negara Malaysia untuk menyediakan perkhidmatan
pengurusan kewangan, kaunseling kredit, pendidikan kewangan dan penstrukturan
semula pembiayaan secara percuma kepada individu. Untuk maklumat berkenaan
perkhidmatan AKPK, sila hubungi talian 03-26167766 atau layari laman sesawang 
www.akpk.org.my</p>
<p style="font-size: 13px; font-family: EmbArial; margin-top:25px;" class="justify">Untuk sebarang pertanyaan, sila hubungi pegawai kami di talian <span style="font-family: EmbArialBold;" >03- xxxx xxxx</span> atau e-mel kepada <span  style="font-family: EmbArialBold;"><u>CCD_Remedial@bankislam.com.my</u></span></p>
<p style="font-size: 13px; font-family: EmbArial;margin-top:30px;">Sekian, terima kasih.</p>
<p style="font-size: 13px; font-family: EmbArial;">Wassalam.</p>
<p style="font-size: 13px; font-family: EmbArial;">Yang benar,</p>
<p style="font-size: 13px; font-family: EmbArialBold;">BANK ISLAM MALAYSIA BERHAD</p>
 
</div>

<div style="margin-top:900px;">   
<p style="font-size: 13px; font-family: EmbArial;text-align: center;">
    Ini adalah cetakan komputer dan tidak memerlukan tandatangan
  </p></div>


</body>

</html>