<!DOCTYPE html>
<html lang="en">

<head>
	<title>Dca Notice-Impaired Bic</title>

	<meta charset="utf-8" />

	<style type="text/css">
		@page {
			size: A4;
			font-family: EmbArial;
			margin-left: 100px;
			margin-right: 100px;
		}

		body {
			font-family: EmbArial;
		}

		.justify {
			text-align: justify;
		}

		.spaced-text {
			display: block;
			padding-left: 30px;
		}
	 table {
            width: 100%;
            border-collapse: collapse;
        }
     
                
    
        
       .not-bold {
            font-weight: normal;
        }
        
            .italic-note {
            font-size: 11px;
            font-family: EmbArialItalic;
            line-height: 0.5;
            margin-top: 2px;
            margin-bottom: 5px;
        }
        
   
             table {
            width: 100%;
            border-collapse: collapse;
        }
          td {
            padding: 1px;
            vertical-align: top;
        }
                
        
       .not-bold {
            font-weight: normal;
        }
 
        
     .paddingTd {
            padding-left: 10px;
            padding-top: 0;
            padding-bottom: 0;
            }
                 .paddingValue {
            padding-left: 10px;
            padding-top: 0;
            padding-bottom: 0;
            }
            
	</style>
</head>

<body style="margin-top: 100px;">	
	<div>
	<div class="justify" style="font-size: 14px; line-height: 1.2;display: inline-block;">
	 <table>
  <tr>
    <td style="font-size: 14px;">No. Akaun</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column B</td>
  </tr>
    <tr>
    <td style="font-size: 14px;">Tarikh</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column C</td>
  </tr>
  </table>

	</div>
	<div style="margin-top: 30px;">
	         <p
          class="justify"
          style="
              font-size: 14px;
              font-family: EmbArialBold;
              margin-top: 0;
              margin-bottom: 0;
              max-height: 90px;
              min-height: 90px;
              height: 90px;              
              ">
          ${contextVariables.name}<span style="margin-left: 250px;">“TANPA PREJUDIS”</span>
          <br />
          <span>
            <#compress>
              <#if contextVariables.add1?has_content && contextVariables.add1?trim !=''>
                ${contextVariables.add1?html}
                <br />
              </#if>
              <#if contextVariables.add2?has_content && contextVariables.add2?trim !=''>
                ${contextVariables.add2?html}
                <br />
              </#if>
              <#if contextVariables.add3?has_content && contextVariables.add3?trim !=''>
                ${contextVariables.add3?html}
                <br />
              </#if>
              <#if contextVariables.add4?has_content && contextVariables.add4?trim !=''>
                ${contextVariables.add4?html}
                <br />
              </#if>
              <#if contextVariables.add5?has_content && contextVariables.add5?trim !=''>
                ${contextVariables.add5?html}
                <br />
              </#if>
              <#if contextVariables.add6?has_content && contextVariables.add6?trim !=''>
                ${contextVariables.add6?html}
              </#if>
            </#compress>
          </span>
        </p>
	</div>
	<p style="font-size: 14px;">Tuan/Puan,</p>
	
	<div  style="display: inline-block;font-size: 14px; font-family: EmbArial;line-height: 1.2;">
	<table> 
	 <tr>
    <td style="font-family: EmbArialBold;">Perkara</td>
    <td class="paddingTd">:</td>
    <td  style="font-family: EmbArialBold;" class="paddingValue">PERMOHONAN PENJADUALAN &amp; PENSTRUKTURAN SEMULA PEMBIAYAAN
 (Type of financing – column J)</td>
  </tr>
  <tr>
    <td style="font-family: EmbArialBold;">Pelanggan</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column D</td>
  </tr>
    <tr>
    <td style="font-family: EmbArialBold;">No. Akaun</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column B</td>
  </tr>
     <tr>
    <td style="font-family: EmbArialBold;">Kemudahan</td>
    <td class="paddingTd">:</td>
    <td class="paddingValue">column J</td>
  </tr>
</table>
	</div>
	
	<div
    style="width: 100%; border: none; border-top: 0.5px solid; border-color: black; margin-bottom: 15px; margin-top: 15px;">
</div>

	<p style="font-size: 14px; font-family: EmbArial;">Perkara di atas adalah dirujuk.</p>
	<p style="font-size: 14px; font-family: EmbArial;" class="justify">Adalah dimaklumkan bahawa permohonan Tuan/Puan untuk mendapat
pengurangan ansuran melalui Penjadualan dan Penstrukturan Semula telah
dibatalkan oleh pihak Bank di atas sebab berikut;</p>
	
	<ul style="list-style-type: square;">
    <li style="font-size: 14px; font-family: EmbArial;" class="justify">
        <p > <span style="margin-left:10px;">Tuan/Puan telah memaklumkan kepada pihak Bank untuk membatalkan</span> <span style="margin-left:10px;">permohonan penjadualan semula</span></p>
    </li>
</ul>
<p style="font-size: 14px; font-family: EmbArial;" class="justify">Pihak Bank menyarankan agar Tuan/Puan mendapatkan bantuan penyelesaian
kewangan daripada pihak Agensi Kaunseling Dan Pengurusan Kredit (AKPK) yang
telah ditubuhkan oleh Bank Negara Malaysia untuk menyediakan perkhidmatan
pengurusan kewangan, kaunseling kredit, pendidikan kewangan dan penstrukturan
semula pembiayaan secara percuma kepada individu. Untuk maklumat berkenaan
perkhidmatan AKPK, sila hubungi talian 03-26167766 atau layari laman sesawang
www.akpk.org.my</p>
<p style="font-size: 14px; font-family: EmbArial;" class="justify">Untuk sebarang pertanyaan, sila hubungi pegawai kami di talian <span style="font-family: EmbArialBold;" >03-xxxx xxxx</span> atau emel kepada <span  style="font-family: EmbArialBold;"><u>CCD_Remedial@bankislam.com.my</u></span></p>
<p style="font-size: 14px; font-family: EmbArial;margin-top:30px;">Sekian, terima kasih.</p>
<p style="font-size: 14px; font-family: EmbArial;">Wassalam.</p>
<p style="font-size: 14px; font-family: EmbArial;">Yang benar,</p>
<p style="font-size: 14px; font-family: EmbArialBold;">BANK ISLAM MALAYSIA BERHAD</p>
<p style="font-size: 14px; font-family: EmbArial; text-align: center; margin-top: 60px;">
    Ini adalah cetakan komputer dan tidak memerlukan tandatangan
</p>



</div>
</body>

</html>