<!DOCTYPE html>
<html lang="en">
  <head>
    <title>reminder</title>

    <meta charset="utf-8" />

    <style type="text/css">
      @page {
        size: A4;
        font-family: EmbArial;
        margin-left: 50px;
        margin-right: 50px;
      }

      body {
        font-family: EmbArial;
      }

      .justify {
        text-align: justify;
      }

      .spaced-text {
        display: block;
        padding-left: 30px;
      }

      .title {
        font-weight: bold;
        font-size: 14px;
        margin-top: 10px;
        padding-left: 250px;
      }

      .not-bold {
        font-weight: normal;
        width: 160px;
      }

      .padding-td {
        padding-left: 10px;
        padding-right: 5px;
        padding-top: 0;
        padding-bottom: 0;
      }

      .section-title {
        font-weight: normal;
        padding-top: 3px;
        font-size: 12px;
      }

      .table {
        width: 100%;
        border-collapse: collapse;
        margin-top: 4px;
        font-size: 12px;
      }

      .table th {
        text-align: left;
        border-top: 1px solid #000;
      }

      .table th {
        font-weight: normal;
        border-bottom: 1px solid #000;
      }

      .footer {
        margin-top: 180px;
        font-size: 12px;
      }

      .tableHeaderInfo {
        border: 1px solid #000;
        text-align: center;
        width: 50%;
        padding: 5px;
      }

      .tableColInfo {
        border: 1px solid #000;
        padding: 5px;
        width: 50%;
      }

      .page-break {
        page-break-before: always;
      }
    </style>
  </head>

  <body>
    <header style="margin-top: 50px; text-align: left; margin-bottom: 20px">
      <div style="display: inline-block">
        <svg
          version="1.0"
          xmlns="http://www.w3.org/2000/svg"
          viewBox="0 0 800.000000 185.000000"
          preserveAspectRatio="xMidYMid meet"
          style="
            vertical-align: middle;
            margin-left: 5px;
            width: 216px;
            height: 50px;
            display: inline-block;
          "
        >
          <g
            transform="translate(0.000000,185.000000) scale(0.100000,-0.100000)"
            fill="#5F6062"
            stroke="none"
          >
            <path
              fill="#C61846"
              d="M4713 1829 c-203 -24 -411 -83 -579 -165 -393 -191 -588 -502 -520
			 -825 54 -252 276 -491 606 -648 586 -280 1403 -245 1883 81 113 77 250 221
			 291 308 9 19 11 27 4 16 -106 -156 -226 -259 -413 -351 -237 -118 -477 -169
			 -790 -168 -468 2 -883 146 -1159 404 -247 231 -316 530 -180 789 127 243 430
			 437 804 516 150 31 336 47 480 41 81 -4 99 -3 60 3 -71 10 -394 10 -487 -1z"
            />
            <path
              d="M1105 1408 c-7 -18 -85 -212 -174 -432 -88 -219 -168 -409 -176 -423
			 -17 -26 -71 -53 -105 -53 -11 0 -20 -4 -20 -9 0 -12 309 -11 316 0 3 5 -10 9
			 -29 9 -70 0 -71 32 -8 195 l39 100 150 3 149 3 53 -142 c49 -131 52 -143 36
			 -154 -15 -12 -15 -13 0 -19 25 -10 553 -5 560 5 3 5 -11 9 -30 9 -22 0 -45 9
			 -62 23 l-27 24 -8 189 c-4 104 -8 244 -8 311 l-1 122 52 -57 c141 -155 635
			 -642 650 -642 16 0 18 13 19 128 0 70 4 268 7 440 l7 314 24 19 c13 10 36 19
			 52 19 16 0 29 5 29 10 0 6 -62 10 -165 10 -103 0 -165 -4 -165 -10 0 -5 18
			 -10 39 -10 23 0 48 -8 62 -19 23 -18 23 -21 32 -331 4 -172 5 -315 2 -318 -3
			 -4 -10 -1 -14 6 -4 7 -115 122 -247 255 -131 133 -284 288 -338 345 -54 56
			 -103 102 -107 102 -15 0 -18 -63 -23 -466 -3 -220 -10 -412 -15 -426 -13 -35
			 -53 -43 -99 -21 -51 25 -77 78 -251 510 -82 204 -154 381 -161 392 -15 30 -29
			 26 -45 -11z m54 -371 c30 -83 56 -158 59 -164 3 -10 -24 -13 -117 -13 -67 0
			 -121 3 -121 8 -1 12 115 322 120 322 3 0 29 -69 59 -153z"
            />
            <path
              d="M6286 1413 c-7 -16 -84 -203 -170 -417 -86 -213 -166 -406 -177 -428
			 -13 -26 -32 -44 -54 -54 -46 -19 -69 -18 -61 2 12 32 19 154 9 154 -6 0 -13
			 -14 -17 -31 -15 -76 -94 -108 -232 -93 -97 10 -110 25 -119 145 -4 52 -5 221
			 -3 375 3 260 4 284 22 303 13 14 31 21 58 21 21 0 38 5 38 10 0 6 -72 10 -195
			 10 -123 0 -195 -4 -195 -10 0 -5 13 -10 30 -10 48 0 79 -20 85 -54 4 -17 5
			 -204 3 -414 l-3 -384 -24 -19 c-13 -10 -36 -19 -53 -19 -16 0 -27 -4 -24 -9 8
			 -12 916 -13 916 -1 0 6 -9 10 -21 10 -35 0 -59 19 -59 47 0 15 19 77 42 140
			 l43 113 150 0 150 0 49 -133 c27 -72 51 -138 53 -144 3 -7 -5 -17 -18 -21
			 l-23 -9 26 -6 c37 -10 508 -6 508 3 0 4 -17 10 -37 14 -58 9 -68 19 -65 69 1
			 43 60 502 66 522 2 6 27 -42 56 -105 63 -134 237 -479 252 -497 6 -7 14 -10
			 19 -7 9 5 182 356 264 536 22 48 43 87 46 88 3 0 18 -91 33 -202 15 -112 31
			 -227 37 -257 13 -77 12 -141 -3 -141 -8 0 -8 -3 -2 -9 14 -15 300 -26 308 -12
			 5 7 -1 11 -16 11 -51 0 -98 21 -113 50 -14 27 -41 196 -112 687 -29 198 -34
			 217 -56 193 -8 -8 -85 -163 -172 -345 -86 -181 -163 -341 -170 -355 -12 -24
			 -21 -10 -159 275 -181 374 -208 427 -223 432 -6 2 -14 -4 -17 -14 -3 -10 -33
			 -198 -66 -418 -33 -220 -65 -417 -70 -437 -26 -92 -100 -76 -155 32 -13 25
			 -85 198 -160 385 -160 398 -185 455 -196 455 -5 0 -15 -12 -23 -27z m53 -388
			 c28 -77 51 -145 51 -152 0 -10 -29 -13 -121 -13 -111 0 -121 1 -114 18 4 9 32
			 84 63 165 34 92 58 143 63 135 4 -8 30 -76 58 -153z"
            />
            <path
              d="M4897 1420 c-229 -58 -266 -295 -74 -464 34 -30 87 -74 117 -98 84
			 -67 115 -117 115 -186 0 -95 -56 -146 -160 -147 -107 0 -173 56 -190 163 -4
			 23 -10 42 -14 42 -10 0 -21 -86 -21 -162 0 -54 2 -58 31 -73 40 -21 160 -34
			 235 -25 162 20 268 145 249 295 -12 100 -58 162 -213 286 -126 101 -152 134
			 -152 197 0 34 6 49 34 79 31 34 39 37 98 41 47 3 74 0 96 -12 35 -18 82 -75
			 82 -99 0 -23 11 -47 21 -47 5 0 9 43 9 95 0 94 0 96 -26 105 -38 15 -193 21
			 -237 10z"
            />
            <path
              d="M0 1400 c0 -5 18 -10 39 -10 23 0 48 -8 62 -19 l24 -19 3 -324 c2
			 -177 -1 -363 -6 -412 -11 -98 -23 -116 -74 -116 -15 0 -28 -4 -28 -9 0 -6 99
			 -9 238 -8 219 2 241 4 283 23 149 69 210 230 135 358 -30 52 -71 88 -138 122
			 l-49 25 49 54 c124 136 81 298 -89 334 -64 14 -449 15 -449 1z m416 -71 c80
			 -73 85 -246 10 -294 -21 -13 -74 -20 -128 -17 l-28 2 0 171 0 171 60 -4 c46
			 -3 66 -10 86 -29z m4 -384 c134 -69 186 -304 85 -380 -68 -53 -202 -40 -225
			 20 -12 30 -14 368 -2 379 10 12 109 -2 142 -19z"
            />
            <path
              d="M2630 1400 c0 -5 18 -10 40 -10 58 0 80 -26 80 -92 3 -436 -1 -727
			 -11 -755 -9 -28 -16 -34 -50 -39 -85 -14 -30 -22 146 -22 182 0 243 9 145 22
			 -37 5 -53 12 -62 29 -14 26 -25 417 -12 417 5 0 15 -9 21 -19 22 -36 269 -315
			 320 -362 80 -75 101 -82 246 -87 134 -5 162 5 78 27 -94 24 -178 96 -429 370
			 l-122 133 33 37 c44 48 266 264 297 289 35 27 97 52 131 52 16 0 29 5 29 10 0
			 6 -58 10 -155 10 -97 0 -155 -4 -155 -10 0 -5 7 -10 15 -10 26 0 16 -43 -21
			 -90 -35 -45 -283 -300 -292 -300 -7 0 4 344 12 363 5 10 24 20 47 23 88 14 28
			 24 -146 24 -117 0 -185 -4 -185 -10z"
            />
            <path
              d="M4270 1400 c0 -5 13 -10 29 -10 16 0 39 -9 52 -19 l24 -19 0 -399 c0
			 -305 -3 -403 -13 -420 -8 -15 -26 -25 -52 -29 -87 -14 -31 -22 155 -22 186 -1
			 263 10 153 20 -92 9 -88 -11 -88 449 0 386 1 400 20 419 11 11 33 20 50 20 17
			 0 30 5 30 10 0 6 -67 10 -180 10 -113 0 -180 -4 -180 -10z"
            />
          </g>
        </svg>

        <div class="title">QUARTERLY STATEMENT</div>
      </div>
    </header>

    <div style="margin-top: 45px; margin-left: 5px">
      <p
        class="justify"
        style="
          font-size: 10px;
          font-family: EmbArialBold;
          margin-top: 0;
          margin-bottom: 0;
        "
      >
        ${contextVariables.name}<br />
        ${contextVariables.address?replace(",", "<br />")}
      </p>
    </div>

    <!-- INFO BOX -->
    <div style="margin-left: 5px; margin-top: 80px">
      <div
        style="
          display: inline-block;
          font-size: 12px;
          font-family: EmbArial;
          line-height: 1.2;
        "
      >
        <table
          style="
            font-weight: normal;
            border-spacing: 0;
            border-collapse: collapse;
          "
        >
          <tr>
            <th class="not-bold" style="padding: 0">Account Number</th>
            <td class="padding-td">:</td>
            <td style="padding: 0">${contextVariables.accountNo!}</td>
          </tr>
          <tr>
            <th class="not-bold" style="padding: 0">
              Unit Trust Consultant (UTC)
            </th>
            <td class="padding-td">:</td>
            <td style="padding: 0">${contextVariables.utc!}</td>
          </tr>
          <tr>
            <th class="not-bold" style="padding: 0">UTC Contact No.</th>
            <td class="padding-td">:</td>
            <td style="padding: 0">${contextVariables.utcContactNo!}</td>
          </tr>
          <tr>
            <th class="not-bold" style="padding: 0">Branch</th>
            <td class="padding-td">:</td>
            <td style="padding: 0">${contextVariables.branch!}</td>
          </tr>
        </table>
      </div>
      <div style="width: 100%; border: none; border-top: 1px solid"></div>

      <!-- TRANSACTION SUMMARY -->
      <div class="section-title">
        1) TRANSACTION SUMMARY AS AT ${contextVariables.date!}
      </div>

      <table class="table">
        <tr>
          <th style="width: 100px; max-width: 100px; vertical-align: top">
            Fund Name
          </th>
          <th style="max-width: 80px; text-align: right; vertical-align: top">
            Previous <br />
            Balance (Unit)
          </th>
          <th style="width: 200px; max-width: 200px; vertical-align: top">
            Name of Joint Holder
          </th>
          <th style="max-width: 100px; text-align: right; vertical-align: top">
            Current <br />
            Balance (Unit)
          </th>
          <th style="max-width: 100px; text-align: right; vertical-align: top">
            NAV (RM)
          </th>
          <th style="max-width: 120px; text-align: right; vertical-align: top">
            Balance (RM)
          </th>
        </tr>

        <tr style="vertical-align: top">
          <td>BANK ISLAM PR EMIER FUND</td>
          <td style="text-align: right">60,132.29</td>
          <td></td>
          <td style="text-align: right">0.00</td>
          <td style="text-align: right">0.9465</td>
          <td style="text-align: right">0.00</td>
        </tr>
      </table>

      <!-- TRANSACTION DETAILS  -->
      <div style="margin-top: 50px">
        <div class="section-title">2) TRANSACTION DETAILS AS AT</div>

        <table class="table">
          <tr style="vertical-align: top">
            <th style="max-width: 25px; min-width: 25px">Trans Type</th>
            <th style="max-width: 30px; min-width: 30px">Prod Type</th>
            <th>Trans No</th>
            <th style="max-width: 62px; min-width: 62px">
              Trans <br />
              Date
            </th>
            <th style="max-width: 75px; min-width: 75px; text-align: right">
              Amount Paid <br />
              (RM)
            </th>
            <th style="max-width: 130px; min-width: 130px; text-align: center">
              &lt;--- Charge Amount ---&gt; <br />
              <div style="display: inline; text-align: right">
                <div
                  style="
                    max-width: 87px;
                    min-width: 87px;
                    display: inline-block;
                  "
                >
                  %
                </div>
                <div
                  style="
                    max-width: 40px;
                    min-width: 40px;
                    display: inline-block;
                  "
                >
                  (RM)
                </div>
              </div>
            </th>
            <th style="max-width: 98px; min-width: 98px; text-align: right">
              Amount Invested/ <br />
              Redeemed (RM)
            </th>
            <th style="max-width: 65px; min-width: 65px; text-align: right">
              NAV (RM)
            </th>
            <th style="max-width: 80px; min-width: 80px; text-align: right">
              Total <br />
              Units
            </th>
          </tr>

          <tr style="vertical-align: top">
            <td>RE</td>
            <td>
              CASH <br />
              PLAN
            </td>
            <td>
              2022002 <br />
              1690
            </td>
            <td>14/10/2022</td>
            <td style="text-align: right">-39,400.49</td>
            <td style="text-align: right">
              <div style="display: inline; text-align: right">
                <div
                  style="
                    max-width: 87px;
                    min-width: 87px;
                    display: inline-block;
                  "
                >
                  0.0000
                </div>
                <div
                  style="
                    max-width: 40px;
                    min-width: 40px;
                    display: inline-block;
                    padding-right: 1px;
                  "
                >
                  0.0
                </div>
              </div>
            </td>
            <td style="text-align: right">0.00</td>
            <td style="text-align: right">0.8730</td>
            <td style="text-align: right">-45,132.29</td>
          </tr>

          <tr style="vertical-align: top">
            <td>RE</td>
            <td>
              CASH <br />
              PLAN
            </td>
            <td>
              2022002 <br />
              0603
            </td>
            <td>12/08/2022</td>
            <td style="text-align: right">-14,137.50</td>
            <td style="text-align: right">
              <div style="display: inline; text-align: right">
                <div
                  style="
                    max-width: 87px;
                    min-width: 87px;
                    display: inline-block;
                  "
                >
                  0.0000
                </div>
                <div
                  style="
                    max-width: 40px;
                    min-width: 40px;
                    display: inline-block;
                  "
                >
                  0.0
                </div>
              </div>
            </td>
            <td style="text-align: right">0.00</td>
            <td style="text-align: right">0.9425</td>
            <td style="text-align: right">-15,000.00</td>
          </tr>
        </table>
      </div>

      <div class="footer">
        <div
          style="
            width: 100%;
            border: none;
            border-top: 1px solid;
            margin-top: 3px;
          "
        ></div>

        <table
          style="
            width: 100%;
            font-size: 10px;
            margin-top: 5px;
            border-collapse: collapse;
          "
        >
          <tr>
            <td>XS : Sales Cancellation</td>
            <td>DV : Distribution Reinvested</td>
            <td>SI : Switch-In</td>
            <td>XR : Redemption Cancellation</td>
          </tr>
          <tr>
            <td>JI : Adjustment In</td>
            <td>RI : Transfer In Cancellation</td>
            <td>SO : Switch-Out</td>
            <td>JO : Adjustment Out</td>
          </tr>
          <tr>
            <td>TI : Transfer-In</td>
            <td>RO : Transfer Out Cancellation</td>
            <td>NS : Investment</td>
            <td>TO : Transfer-Out</td>
          </tr>
          <tr>
            <td>RE : Redemption</td>
            <td>XI : Switch In Cancellation</td>
            <td>US : Unit Split</td>
            <td>XO : Switch Out Cancellation</td>
          </tr>
          <tr>
            <td>CP : Capital Repayment</td>
            <td colspan="3"></td>
          </tr>
        </table>
        <div
          style="
            width: 100%;
            border: none;
            border-top: 1px solid;
            margin-top: 3px;
            margin-bottom: -10px;
          "
        ></div>
        <p>
          This is computer generated advice and no signature is required. Please
          advise Bank Islam within seven (7) business days from the date of
          issuance of this advice if there is any discrepancy. For any change of
          information, kindly visit our nearest branch.
        </p>
        <p>
          <strong>Bank Islam Malaysia Berhad</strong>(No. 98127-X), Level 32,
          Menara Bank Islam, No. 22, Jalan Perak, 50450 Kuala Lumpur.<br />
          Tel: (603) 2088 8000 Fax: (603) 2088 8028 Telex: MA 31783 Swift:
          BIMBMYKL www.bankislam.com.my
        </p>
      </div>

      <!-- PAGE BREAK -->
      <div class="page-break"></div>

      <!-- PURPOSE AND CONTACT INFORMATION -->
      <table
        style="
          width: 100%;
          border-collapse: collapse;
          font-size: 12px;
          margin-top: 50px;
        "
      >
        <tr style="vertical-align: top">
          <th class="tableHeaderInfo">Purpose</th>
          <th class="tableHeaderInfo">Contact Information</th>
        </tr>
        <tr style="vertical-align: top">
          <td class="tableColInfo">Suggestion,Compliment or Complaint</td>
          <td class="tableColInfo">
            Bank Islam Contact Centre<br />
            Telephone No.: 03-26 900 900 <br />
            email: contactcenter@bankislam.com.my
          </td>
        </tr>
        <tr style="vertical-align: top">
          <td class="tableColInfo">
            Unit Trust Operation Related Matter i.e Statement and Reporting
          </td>
          <td class="tableColInfo">
            Unit Trust Operation<br />
            Wealth Management Operation and Ar-Rahnu<br />
            29th Floor, Menara Bank Islam<br />
            No.22 Jalan Perak<br />
            50450 Kuala Lumpur<br /><br />
            Telephone no.:
            <div>03-2088 8091/03-2088 8370/03-2088 811 (930am-4.30pm)</div>
            email : IUTA@bankislam.com.my
          </td>
        </tr>
        <tr style="vertical-align: top">
          <td class="tableColInfo">
            Unit Trust Sales Related Matter i.e Unit Trust Product, Unit Trust
            Investment Performance, Unit Trust Application Processing
          </td>
          <td class="tableColInfo">
            Branch i.e Sales Person, Wealth Executive
          </td>
        </tr>
      </table>
    </div>
  </body>
</html>
