<!DOCTYPE html>
<html lang="en">

<head>
  <title>Wealth Management-Quarterly Statement</title>

  <meta charset="utf-8" />

  <style type="text/css">
    @page {
      size: A4;
      font-family: EmbArial;
      margin-left: 50px;
      margin-right: 50px;

      @bottom-center {
        content: "Page " counter(page) " / " counter(pages);
        font-size: 12px;
      }
    }

    body {
      font-family: EmbArial;
    }

    .justify {
      text-align: justify;
    }

    .spaced-text {
      display: block;
      padding-left: 30px;
    }

    .title {
      font-size: 14px;
      margin-top: 10px;
      padding-left: 250px;
      font-family: EmbArialBold;
      font-weight: normal;
    }

    .not-bold {
      font-weight: normal;
      width: 160px;
    }

    .padding-td {
      padding-left: 10px;
      padding-right: 5px;
      padding-top: 0;
      padding-bottom: 0;
    }

    .section-title {
      font-weight: normal;
      padding: 2px;
      font-size: 12px;
      border-bottom: 1px dashed;
    }

    .table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 4px;
      font-size: 12px;
    }

    .table th {
      text-align: left;
      font-weight: normal;
      border-bottom: 0.5px solid;
    }

    /* .table th {
        font-weight: normal;
        border-bottom: 0.5px solid;
      } */

    .footer {
      margin-top: 160px;
      font-size: 12px;
    }

    .tableHeaderInfo {
      border: 1px solid #000;
      text-align: center;
      width: 50%;
      padding: 5px;
      font-family: EmbArialBold;
      font-weight: normal;
    }

    .tableColInfo {
      border: 1px solid #000;
      padding: 5px;
      width: 50%;
    }

    .page-break {
      page-break-before: always;
    }

    .info {
      padding-left: 30px;
    }

    .boldInfo {
      font-family: EmbArialBold;
    }

    .break {
      /* table-layout: fixed;
  width: 180px;   */
      word-wrap: break-word;
      white-space: normal;
      overflow-wrap: break-word;
    }
  </style>
</head>

<body>
  <header style=" text-align: left; margin-bottom: 20px">
    <div style="display: inline-block">
      <svg version="1.0" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800.000000 185.000000"
        preserveAspectRatio="xMidYMid meet" style="
            vertical-align: middle;
            margin-left: 5px;
            width: 216px;
            height: 50px;
            display: inline-block;
          ">
        <g transform="translate(0.000000,185.000000) scale(0.100000,-0.100000)" fill="#5F6062" stroke="none">
          <path fill="#C61846" d="M4713 1829 c-203 -24 -411 -83 -579 -165 -393 -191 -588 -502 -520
			 -825 54 -252 276 -491 606 -648 586 -280 1403 -245 1883 81 113 77 250 221
			 291 308 9 19 11 27 4 16 -106 -156 -226 -259 -413 -351 -237 -118 -477 -169
			 -790 -168 -468 2 -883 146 -1159 404 -247 231 -316 530 -180 789 127 243 430
			 437 804 516 150 31 336 47 480 41 81 -4 99 -3 60 3 -71 10 -394 10 -487 -1z" />
          <path d="M1105 1408 c-7 -18 -85 -212 -174 -432 -88 -219 -168 -409 -176 -423
			 -17 -26 -71 -53 -105 -53 -11 0 -20 -4 -20 -9 0 -12 309 -11 316 0 3 5 -10 9
			 -29 9 -70 0 -71 32 -8 195 l39 100 150 3 149 3 53 -142 c49 -131 52 -143 36
			 -154 -15 -12 -15 -13 0 -19 25 -10 553 -5 560 5 3 5 -11 9 -30 9 -22 0 -45 9
			 -62 23 l-27 24 -8 189 c-4 104 -8 244 -8 311 l-1 122 52 -57 c141 -155 635
			 -642 650 -642 16 0 18 13 19 128 0 70 4 268 7 440 l7 314 24 19 c13 10 36 19
			 52 19 16 0 29 5 29 10 0 6 -62 10 -165 10 -103 0 -165 -4 -165 -10 0 -5 18
			 -10 39 -10 23 0 48 -8 62 -19 23 -18 23 -21 32 -331 4 -172 5 -315 2 -318 -3
			 -4 -10 -1 -14 6 -4 7 -115 122 -247 255 -131 133 -284 288 -338 345 -54 56
			 -103 102 -107 102 -15 0 -18 -63 -23 -466 -3 -220 -10 -412 -15 -426 -13 -35
			 -53 -43 -99 -21 -51 25 -77 78 -251 510 -82 204 -154 381 -161 392 -15 30 -29
			 26 -45 -11z m54 -371 c30 -83 56 -158 59 -164 3 -10 -24 -13 -117 -13 -67 0
			 -121 3 -121 8 -1 12 115 322 120 322 3 0 29 -69 59 -153z" />
          <path d="M6286 1413 c-7 -16 -84 -203 -170 -417 -86 -213 -166 -406 -177 -428
			 -13 -26 -32 -44 -54 -54 -46 -19 -69 -18 -61 2 12 32 19 154 9 154 -6 0 -13
			 -14 -17 -31 -15 -76 -94 -108 -232 -93 -97 10 -110 25 -119 145 -4 52 -5 221
			 -3 375 3 260 4 284 22 303 13 14 31 21 58 21 21 0 38 5 38 10 0 6 -72 10 -195
			 10 -123 0 -195 -4 -195 -10 0 -5 13 -10 30 -10 48 0 79 -20 85 -54 4 -17 5
			 -204 3 -414 l-3 -384 -24 -19 c-13 -10 -36 -19 -53 -19 -16 0 -27 -4 -24 -9 8
			 -12 916 -13 916 -1 0 6 -9 10 -21 10 -35 0 -59 19 -59 47 0 15 19 77 42 140
			 l43 113 150 0 150 0 49 -133 c27 -72 51 -138 53 -144 3 -7 -5 -17 -18 -21
			 l-23 -9 26 -6 c37 -10 508 -6 508 3 0 4 -17 10 -37 14 -58 9 -68 19 -65 69 1
			 43 60 502 66 522 2 6 27 -42 56 -105 63 -134 237 -479 252 -497 6 -7 14 -10
			 19 -7 9 5 182 356 264 536 22 48 43 87 46 88 3 0 18 -91 33 -202 15 -112 31
			 -227 37 -257 13 -77 12 -141 -3 -141 -8 0 -8 -3 -2 -9 14 -15 300 -26 308 -12
			 5 7 -1 11 -16 11 -51 0 -98 21 -113 50 -14 27 -41 196 -112 687 -29 198 -34
			 217 -56 193 -8 -8 -85 -163 -172 -345 -86 -181 -163 -341 -170 -355 -12 -24
			 -21 -10 -159 275 -181 374 -208 427 -223 432 -6 2 -14 -4 -17 -14 -3 -10 -33
			 -198 -66 -418 -33 -220 -65 -417 -70 -437 -26 -92 -100 -76 -155 32 -13 25
			 -85 198 -160 385 -160 398 -185 455 -196 455 -5 0 -15 -12 -23 -27z m53 -388
			 c28 -77 51 -145 51 -152 0 -10 -29 -13 -121 -13 -111 0 -121 1 -114 18 4 9 32
			 84 63 165 34 92 58 143 63 135 4 -8 30 -76 58 -153z" />
          <path d="M4897 1420 c-229 -58 -266 -295 -74 -464 34 -30 87 -74 117 -98 84
			 -67 115 -117 115 -186 0 -95 -56 -146 -160 -147 -107 0 -173 56 -190 163 -4
			 23 -10 42 -14 42 -10 0 -21 -86 -21 -162 0 -54 2 -58 31 -73 40 -21 160 -34
			 235 -25 162 20 268 145 249 295 -12 100 -58 162 -213 286 -126 101 -152 134
			 -152 197 0 34 6 49 34 79 31 34 39 37 98 41 47 3 74 0 96 -12 35 -18 82 -75
			 82 -99 0 -23 11 -47 21 -47 5 0 9 43 9 95 0 94 0 96 -26 105 -38 15 -193 21
			 -237 10z" />
          <path d="M0 1400 c0 -5 18 -10 39 -10 23 0 48 -8 62 -19 l24 -19 3 -324 c2
			 -177 -1 -363 -6 -412 -11 -98 -23 -116 -74 -116 -15 0 -28 -4 -28 -9 0 -6 99
			 -9 238 -8 219 2 241 4 283 23 149 69 210 230 135 358 -30 52 -71 88 -138 122
			 l-49 25 49 54 c124 136 81 298 -89 334 -64 14 -449 15 -449 1z m416 -71 c80
			 -73 85 -246 10 -294 -21 -13 -74 -20 -128 -17 l-28 2 0 171 0 171 60 -4 c46
			 -3 66 -10 86 -29z m4 -384 c134 -69 186 -304 85 -380 -68 -53 -202 -40 -225
			 20 -12 30 -14 368 -2 379 10 12 109 -2 142 -19z" />
          <path d="M2630 1400 c0 -5 18 -10 40 -10 58 0 80 -26 80 -92 3 -436 -1 -727
			 -11 -755 -9 -28 -16 -34 -50 -39 -85 -14 -30 -22 146 -22 182 0 243 9 145 22
			 -37 5 -53 12 -62 29 -14 26 -25 417 -12 417 5 0 15 -9 21 -19 22 -36 269 -315
			 320 -362 80 -75 101 -82 246 -87 134 -5 162 5 78 27 -94 24 -178 96 -429 370
			 l-122 133 33 37 c44 48 266 264 297 289 35 27 97 52 131 52 16 0 29 5 29 10 0
			 6 -58 10 -155 10 -97 0 -155 -4 -155 -10 0 -5 7 -10 15 -10 26 0 16 -43 -21
			 -90 -35 -45 -283 -300 -292 -300 -7 0 4 344 12 363 5 10 24 20 47 23 88 14 28
			 24 -146 24 -117 0 -185 -4 -185 -10z" />
          <path d="M4270 1400 c0 -5 13 -10 29 -10 16 0 39 -9 52 -19 l24 -19 0 -399 c0
			 -305 -3 -403 -13 -420 -8 -15 -26 -25 -52 -29 -87 -14 -31 -22 155 -22 186 -1
			 263 10 153 20 -92 9 -88 -11 -88 449 0 386 1 400 20 419 11 11 33 20 50 20 17
			 0 30 5 30 10 0 6 -67 10 -180 10 -113 0 -180 -4 -180 -10z" />
        </g>
      </svg>
    </div>
    <svg version="1.0" xmlns="http://www.w3.org/2000/svg" width="386.000000pt" height="295.000000pt"
      viewBox="0 0 386.000000 295.000000" preserveAspectRatio="xMidYMid meet" style="
        width: 100px;
        height: 70px;
        display: inline-block;
        vertical-align: middle;
        margin-left: 350px;
      ">
      <g transform="translate(0.000000,295.000000) scale(0.100000,-0.100000)" fill="#000000" stroke="none">
        <path d="M2550 2693 c-275 -31 -615 -161 -890 -341 -112 -73 -288 -211 -330
-258 -14 -16 -4 -10 22 13 228 204 585 396 891 478 202 55 435 71 581 40 149
-32 270 -116 323 -224 25 -51 28 -66 27 -166 0 -98 -3 -119 -31 -191 -35 -94
-94 -198 -154 -275 -24 -30 -32 -45 -20 -35 71 63 192 256 231 372 102 294
-26 516 -332 578 -71 15 -228 19 -318 9z" />
        <path d="M2515 2600 c-322 -29 -730 -205 -1024 -440 -174 -139 -321 -307 -404
-460 -72 -131 -99 -290 -69 -397 36 -126 165 -222 342 -255 90 -17 328 -4 450
25 435 103 882 386 1135 717 66 87 148 251 165 331 19 84 10 204 -19 263 -79
160 -295 242 -576 216z m-105 -191 c73 -34 123 -79 151 -135 33 -68 24 -168
-22 -254 -44 -84 -159 -198 -277 -275 l-92 -60 0 -142 c0 -116 -4 -152 -19
-193 -23 -61 -87 -150 -108 -150 -11 0 -13 5 -7 18 4 9 11 181 14 382 7 413
10 428 85 506 49 51 71 57 60 17 -22 -86 -37 -403 -19 -403 18 0 150 109 211
174 115 120 163 246 128 334 -40 98 -141 147 -305 147 -118 -1 -193 -21 -311
-82 -214 -111 -379 -350 -379 -547 1 -161 134 -278 258 -227 40 17 40 26 2 46
-96 50 -93 111 12 211 72 70 96 84 140 84 87 0 109 -101 47 -222 -65 -127
-265 -268 -382 -268 -96 0 -157 88 -165 237 -10 195 70 391 228 557 116 122
234 197 380 244 97 31 97 31 210 29 89 -2 114 -7 160 -28z m-351 -175 c10 -23
8 -31 -18 -65 l-29 -40 -21 27 -21 26 31 39 c17 22 34 39 38 39 4 0 13 -12 20
-26z m49 -79 c11 -23 8 -29 -22 -62 l-33 -37 -17 27 c-17 25 -17 27 11 62 33
42 46 44 61 10z m-121 -22 c13 -19 11 -24 -18 -57 -30 -35 -33 -36 -50 -20
-25 22 -24 29 9 70 30 37 38 38 59 7z" />
        <path d="M1204 1968 l-19 -23 23 19 c21 18 27 26 19 26 -2 0 -12 -10 -23 -22z" />
        <path d="M1154 1908 l-19 -23 23 19 c21 18 27 26 19 26 -2 0 -12 -10 -23 -22z" />
        <path d="M1080 1813 c-64 -86 -135 -229 -156 -313 -24 -96 -16 -220 19 -292
32 -65 104 -136 176 -172 169 -86 451 -89 743 -7 283 80 579 235 815 425 45
36 85 71 89 78 4 6 -24 -13 -62 -44 -236 -190 -624 -375 -908 -433 -399 -81
-692 -3 -799 214 -29 60 -32 74 -31 156 0 55 7 113 18 150 21 70 81 194 126
259 48 70 26 55 -30 -21z" />
        <path d="M2904 1668 l-19 -23 23 19 c21 18 27 26 19 26 -2 0 -12 -10 -23 -22z" />
        <path d="M2814 1578 l-19 -23 23 19 c21 18 27 26 19 26 -2 0 -12 -10 -23 -22z" />
        <path d="M1030 710 c0 -60 4 -100 10 -100 6 0 10 17 10 39 0 37 1 39 40 45 24
4 43 14 50 25 27 51 -3 91 -68 91 l-42 0 0 -100z m88 63 c17 -33 -4 -63 -45
-63 -20 0 -23 5 -23 40 0 38 2 40 30 40 18 0 33 -7 38 -17z" />
        <path d="M1250 710 l0 -100 55 0 c30 0 55 5 55 10 0 6 -21 10 -46 10 l-45 0 3
38 c3 35 5 37 41 40 50 4 48 22 -3 22 -38 0 -40 2 -40 30 0 28 2 30 40 30 22
0 40 5 40 10 0 6 -22 10 -50 10 l-50 0 0 -100z" />
        <path d="M1450 710 c0 -82 3 -100 15 -100 11 0 15 12 15 45 0 37 3 45 19 45
22 0 35 -15 48 -54 13 -40 36 -48 27 -9 -3 15 -12 38 -20 50 -11 18 -11 23 1
33 22 18 19 67 -4 80 -11 5 -38 10 -60 10 l-41 0 0 -100z m95 60 c9 -27 -11
-50 -41 -50 -21 0 -24 5 -24 35 0 32 2 35 29 35 21 0 32 -6 36 -20z" />
        <path d="M1670 710 l0 -100 40 0 c30 0 47 7 65 25 30 29 31 39 7 63 -16 16
-17 22 -5 37 30 42 2 75 -63 75 l-44 0 0 -100z m85 50 c0 -20 -6 -26 -27 -28
-25 -3 -28 0 -28 28 0 28 3 31 28 28 21 -2 27 -8 27 -28z m-4 -60 c37 -20 17
-70 -28 -70 -20 0 -23 5 -23 40 0 43 13 50 51 30z" />
        <path d="M1916 723 c-16 -49 -31 -94 -33 -100 -3 -7 0 -13 6 -13 7 0 17 14 22
30 10 26 16 30 49 30 33 0 39 -4 49 -30 9 -28 36 -44 29 -17 -24 89 -65 187
-78 187 -11 0 -24 -26 -44 -87z m53 35 c25 -67 25 -68 -9 -68 -27 0 -31 3 -25
18 3 9 9 29 12 45 7 33 11 34 22 5z" />
        <path d="M2130 710 c0 -82 3 -100 15 -100 12 0 15 16 15 82 l0 81 48 -78 c26
-43 53 -81 60 -83 9 -3 12 21 12 97 0 118 -18 138 -22 26 l-3 -75 -45 75 c-28
47 -51 75 -62 75 -16 0 -18 -11 -18 -100z" />
        <path d="M2390 710 c0 -60 4 -100 10 -100 6 0 10 17 10 38 0 65 19 69 57 12
18 -28 40 -50 49 -50 10 0 3 17 -25 58 l-39 58 35 42 c48 59 18 54 -34 -5
l-42 -48 -1 48 c0 26 -4 47 -10 47 -6 0 -10 -40 -10 -100z" />
        <path d="M2636 723 c-16 -49 -31 -94 -33 -100 -3 -7 0 -13 6 -13 7 0 17 14 22
30 10 26 16 30 49 30 33 0 39 -4 49 -30 5 -16 15 -30 20 -30 16 0 15 6 -21
108 -42 120 -55 120 -92 5z m58 23 c3 -13 9 -31 12 -40 5 -13 -1 -16 -26 -16
-25 0 -31 3 -26 16 3 9 9 27 12 40 3 13 10 24 14 24 4 0 11 -11 14 -24z" />
        <path d="M2852 713 c2 -66 7 -98 16 -101 9 -3 12 17 12 79 l0 82 48 -78 c26
-43 53 -81 60 -83 9 -3 12 21 12 97 0 118 -18 138 -22 26 l-3 -75 -45 75 c-29
48 -51 75 -63 75 -16 0 -17 -9 -15 -97z" />
        <path d="M1682 444 c-34 -23 -26 -62 18 -92 46 -31 54 -47 33 -67 -11 -11 -26
-15 -44 -11 -36 7 -48 -11 -13 -20 88 -22 129 71 49 109 -41 20 -53 41 -34 63
9 11 22 14 41 10 30 -6 39 8 12 18 -24 9 -38 7 -62 -10z" />
        <path d="M1530 349 c0 -76 3 -100 13 -97 8 3 13 35 15 101 2 82 0 97 -13 97
-12 0 -15 -17 -15 -101z" />
        <path d="M1870 350 l0 -100 49 0 c62 0 77 18 19 22 l-43 3 -3 88 c-4 121 -22
111 -22 -13z" />
        <path d="M2115 438 c-23 -61 -55 -164 -55 -175 0 -26 19 -12 30 22 10 31 16
35 46 35 29 0 36 -5 50 -37 29 -65 26 -13 -4 77 -19 56 -34 86 -45 88 -10 2
-19 -2 -22 -10z m44 -85 c1 -7 -10 -13 -24 -13 -29 0 -29 0 -13 53 l12 40 12
-34 c7 -19 13 -40 13 -46z" />
        <path d="M2316 433 c-10 -34 -10 -168 -1 -171 6 -1 12 33 15 75 6 87 8 86 39
-9 13 -38 28 -68 35 -68 7 0 23 34 36 75 13 41 27 75 31 75 5 0 9 -34 11 -75
2 -41 7 -75 12 -75 9 0 9 151 -1 176 -12 32 -37 7 -59 -60 -13 -38 -26 -71
-28 -73 -2 -2 -15 29 -28 69 -25 73 -51 99 -62 61z" />
      </g>
    </svg>
    <div class="title">QUARTERLY STATEMENT</div>
  </header>

  <div style="margin-top: 30px; margin-left: 5px">
    <p class="justify" style="
          font-size: 10px;
          font-family: EmbArial;
          margin-top: 0;
          margin-bottom: 0;
        ">
      ${contextVariables.name}
      ${contextVariables.add1?replace(",", "<br />")}
      ${contextVariables.add2?replace(",", "<br />")}
      ${contextVariables.add4?replace(",", "<br />")}
      ${contextVariables.add5?replace(",", "<br />")}
      ${contextVariables.poscode?replace(",", "<br />")}
      ${contextVariables.add6?replace(",", "<br />")}
      ${contextVariables.add7?replace(",", "<br />")}
    </p>
  </div>

  <!-- INFO BOX -->
  <div style="margin-left: 5px; margin-top: 50px">
    <div style="
          display: inline-block;
          font-size: 12px;
          font-family: EmbArial;
          line-height: 1.2;
        ">
      <table style="
            font-weight: normal;
            border-spacing: 0;
            border-collapse: collapse;
          ">
        <tr>
          <th class="not-bold" style="padding: 0">Account Number</th>
          <td class="padding-td">:</td>
          <td style="padding: 0">${contextVariables.accountNo!}</td>
        </tr>
        <tr>
          <th class="not-bold" style="padding: 0">
            Unit Trust Consultant (UTC)
          </th>
          <td class="padding-td">:</td>
          <td style="padding: 0">${contextVariables.unitTrustConsultant!}</td>
        </tr>
        <tr>
          <th class="not-bold" style="padding: 0">UTC Contact No.</th>
          <td class="padding-td">:</td>
          <td style="padding: 0">${contextVariables.unitTrustContactNo!}</td>
        </tr>
        <tr>
          <th class="not-bold" style="padding: 0">Branch</th>
          <td class="padding-td">:</td>
          <td style="padding: 0">${contextVariables.branchName!}</td>
        </tr>
      </table>
    </div>
    <div style="width: 100%; border: none; border-top: 1px dashed"></div>

    <!-- TRANSACTION SUMMARY -->
    <div class="section-title">
      1) TRANSACTION SUMMARY AS AT ${contextVariables.date!}
    </div>

    <table class="table">
      <tr>
        <th style="width: 100px; max-width: 100px; vertical-align: top; padding-left: 15px;">
          Fund Name
        </th>
        <th style="max-width: 80px; text-align: right; vertical-align: top">
          Previous<br />
          Balance (Unit)
        </th>
        <th style="width: 200px; max-width: 200px; vertical-align: top">
          &#160; Name of Joint Holder
        </th>
        <th style="max-width: 100px; text-align: right; vertical-align: top">
          Current<br />
          Balance (Unit)
        </th>
        <th style="max-width: 100px; text-align: right; vertical-align: top">
          NAV (RM)
        </th>
        <th style="max-width: 120px; text-align: right; vertical-align: top">
          Balance (RM)
        </th>
      </tr>

      <tr style="vertical-align: top;">
        <td class="break" style="padding-left: 15px;">${contextVariables.fundName!}</td>
        <td class="break" style="text-align: right">${contextVariables.previousBalanceUnit!}</td>
        <td class="break">&#160;${contextVariables.nameOfJointHolder!}</td>
        <td class="break" style="text-align: right">${contextVariables.currentBalanceUnit!}</td>
        <td class="break" style="text-align: right">${contextVariables.currentNav!}</td>
        <td class="break" style="text-align: right">${contextVariables.balance!}</td>
      </tr>
    </table>

    <!-- TRANSACTION DETAILS  -->
    <div style="margin-top: 40px">
      <div class="section-title">
        2) TRANSACTION DETAILS AS AT ${contextVariables.date!}
      </div>

      <table class="table">
        <tr style="vertical-align: top">
          <th style="max-width: 35px; min-width: 35px;padding-left: 15px;">Trans Type</th>
          <th style="max-width: 30px; min-width: 30px">Prod Type</th>
          <th>Trans <br />No</th>
          <th style="max-width: 62px; min-width: 62px">
            Trans <br />
            Date
          </th>
          <th style="max-width: 75px; min-width: 75px; text-align: right">
            Amount Paid<br />
            (RM)
          </th>
          <th style="max-width: 134px; min-width: 134px; text-align: center;">
            &lt;--- Charge Amount ---&gt; <br />
            <div style="display: inline; text-align: right">
              <div style="
                      max-width: 65px;
                      min-width: 65px;
                      display: inline-block;
                    ">
                %
              </div>
              <div style="
                      max-width: 55px;
                      min-width: 55px;
                      display: inline-block;
                    ">
                (RM)
              </div>
            </div>
          </th>
          <th style="max-width: 98px; min-width: 98px; text-align: right">
            Amt Invested/<br />
            Redeemed (RM)
          </th>
          <th style="max-width: 65px; min-width: 65px; text-align: right">
            NAV (RM)
          </th>
          <th style="max-width: 80px; min-width: 80px; text-align: right">
            Total<br />
            Units
          </th>
        </tr>

        <#list contextVariables.rows as row>
          <tr style="vertical-align: top">
            <td style="padding-left: 15px;" class="break">${row.transactionType}</td>
            <td class="break">
              ${row.productType}
            </td>
            <td class="break">
              ${row.transactionNo}
            </td>
            <td class="break">${row.transactionDate?datetime("yyyy-MM-dd")?string("dd/MM/yyyy")}</td>
            <td class="break" style="text-align: right">${row.amountPaid}</td>
            <td class="break" style="text-align: right">
              <div style="display: inline; text-align: right">
                <div style="
                      max-width: 60px;
                      min-width: 60px;
                      display: inline-block;
                    ">
                  ${row.chargeAmountPercentage}
                </div>
                <div style="
                      max-width: 60px;
                      min-width: 60px;
                      display: inline-block;
                      padding-right: 1px;
                    ">
                  ${row.chargeAmountRm}
                </div>
              </div>
            </td>
            <td class="break" style="text-align: right">${row.amountInvestedRedeemed}</td>
            <td class="break" style="text-align: right">${row.nav}</td>
            <td class="break" style="text-align: right">${row.totalUnits}</td>
          </tr>
        </#list>
      </table>
    </div>

    <div class="footer">
      <div style="
            width: 100%;
            border: none;
            border-top: 1px dashed;
            margin-top: 3px;
          "></div>

      <table>
        <tr>
          <td style="padding-left: 13px;">XS</td>
          <td>:</td>
          <td>Sales Cancellation</td>
          <td class="info">DV</td>
          <td>:</td>
          <td>Distribution Reinvested</td>
          <td class="info">SI</td>
          <td>:</td>
          <td>Switch-In</td>
          <td class="info">XR</td>
          <td>:</td>
          <td>Redemption Cancellcation</td>
        </tr>
        <tr>
          <td style="padding-left: 13px;">JI</td>
          <td>:</td>
          <td>Adjustment In</td>
          <td class="info">RI</td>
          <td>:</td>
          <td>Transfer In Cancellation</td>
          <td class="info">SO</td>
          <td>:</td>
          <td>Switch-Out</td>
          <td class="info">JO</td>
          <td>:</td>
          <td>Adjustment Out</td>
        </tr>
        <tr>
          <td style="padding-left: 13px;">TI</td>
          <td>:</td>
          <td>Transfer-In</td>
          <td class="info">RO</td>
          <td>:</td>
          <td>Transfer Out Cancellation</td>
          <td class="info">NS</td>
          <td>:</td>
          <td>Investment</td>
          <td class="info">TO</td>
          <td>:</td>
          <td>Transfer-Out</td>
        </tr>
        <tr>
          <td style="padding-left: 13px;">RE</td>
          <td>:</td>
          <td>Redemption</td>
          <td class="info">XI</td>
          <td>:</td>
          <td>Switch In Cancellation</td>
          <td class="info">US</td>
          <td>:</td>
          <td>Unit Split</td>
          <td class="info">XO</td>
          <td>:</td>
          <td>Switch Out Cancellation</td>
        </tr>
        <tr>
          <td style="padding-left: 13px;">CP</td>
          <td>:</td>
          <td>Capital Repayment</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </table>
      <div style="
            width: 100%;
            border: none;
            border-top: 1px dashed;
            margin-top: 3px;
            margin-bottom: -10px;
          "></div>
      <p style="text-align: justify">
        This is computer generated advice and no signature is required. Please
        advise Bank Islam within seven (7) business days from the date of
        issuance of this advice if there is any discrepancy. For any change of
        information, kindly visit our nearest branch.
      </p>
      <span style="margin-left: 40px">
        <span class="boldInfo">Bank Islam Malaysia Berhad</span><span style="font-size: 8px"> (No. 98127-X)</span> Level
        32, Menara
        Bank Islam, No. 22, Jalan Perak, 50450 Kuala Lumpur.<br /> </span><span style="margin-left: 70px">Tel: (603)
        2088 8000 &#160;Fax: (603) 2088 8028 &#160;Telex: MA 31783 &#160;Swift:
        BIMBMYKL &#160;www.bankislam.com.my
      </span>
    </div>

    <!-- PAGE BREAK -->
    <div class="page-break"></div>

    <!-- PURPOSE AND CONTACT INFORMATION -->
    <table style="
          width: 100%;
          border-collapse: collapse;
          font-size: 12px;
          margin-top: 50px;
        ">
      <tr style="vertical-align: top">
        <th class="tableHeaderInfo">Purpose</th>
        <th class="tableHeaderInfo">Contact Information</th>
      </tr>
      <tr style="vertical-align: top">
        <td class="tableColInfo">Suggestion, Compliment or Complaint</td>
        <td class="tableColInfo">
          Bank Islam Contact Centre<br />
          Telephone No. : 03-26 900 900 <br />
          email: contactcenter@bankislam.com.my
        </td>
      </tr>
      <tr style="vertical-align: top">
        <td class="tableColInfo">
          Unit Trust Operation Related Matter i.e Statement and Reporting
        </td>
        <td class="tableColInfo">
          Unit Trust Operation<br />
          Wealth Management Operation and Ar-Rahnu<br />
          29<sup>th</sup> Floor, Menara Bank Islam<br />
          No.22 Jalan Perak<br />
          50450 Kuala Lumpur<br /><br />
          <div>
            Telephone no. :
            <span>03-2088 8091 / 03-2088 8370 / 03-2088 811</span>
          </div>
          <div style="margin-left: 84px">(9.30am-4.30pm)</div>
          <div>
            email
            <span style="margin-left: 45px">:</span> IUTA@bankislam.com.my
          </div>
        </td>
      </tr>
      <tr style="vertical-align: top">
        <td class="tableColInfo">
          Unit Trust Sales Related Matter i.e Unit Trust Product, Unit Trust
          Investment Performance, Unit Trust Application Processing
        </td>
        <td class="tableColInfo">
          Branch i.e Sales Person, Wealth Executive
        </td>
      </tr>
    </table>
  </div>
</body>

</html>